
version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: UNID_DB
    user: root
    environment:
      POSTGRES_USER: postgres # default
      POSTGRES_PASSWORD: password # password sample
      POSTGRES_DB: database_name # database name sample
    ports:
      - 5432:5432
